var hierarchy =
[
    [ "xmc::AttributeBufferClass< T >", "classxmc_1_1AttributeBufferClass.html", null ],
    [ "xmc::baked_vertex_t", "structxmc_1_1baked__vertex__t.html", null ],
    [ "xmc::color4444", "unionxmc_1_1color4444.html", null ],
    [ "xmc::colorf", "structxmc_1_1colorf.html", null ],
    [ "GFXfont", "structGFXfont.html", null ],
    [ "GFXglyph", "structGFXglyph.html", null ],
    [ "xmc::IndexBufferClass", "classxmc_1_1IndexBufferClass.html", null ],
    [ "xmc::mat4", "structxmc_1_1mat4.html", null ],
    [ "xmc::MaterialClass", "classxmc_1_1MaterialClass.html", null ],
    [ "xmc::MeshClass", "classxmc_1_1MeshClass.html", null ],
    [ "xmc::Mixer", "classxmc_1_1Mixer.html", null ],
    [ "xmc::PrimitiveClass", "classxmc_1_1PrimitiveClass.html", null ],
    [ "xmc::quat", "structxmc_1_1quat.html", null ],
    [ "xmc::RasterizerClass", "classxmc_1_1RasterizerClass.html", null ],
    [ "xmc::rect_t", "structxmc_1_1rect__t.html", null ],
    [ "xmc::SpriteClass", "classxmc_1_1SpriteClass.html", [
      [ "xmc::Sprite4444Class", "classxmc_1_1Sprite4444Class.html", null ],
      [ "xmc::Sprite444Class", "classxmc_1_1Sprite444Class.html", null ],
      [ "xmc::Sprite565Class", "classxmc_1_1Sprite565Class.html", null ]
    ] ],
    [ "xmc::Tone", "classxmc_1_1Tone.html", null ],
    [ "xmc::vec2", "structxmc_1_1vec2.html", null ],
    [ "xmc::vec3", "structxmc_1_1vec3.html", null ],
    [ "xmc_app_config_t", "structxmc__app__config__t.html", null ],
    [ "xmc_audio_format_t", "structxmc__audio__format__t.html", null ],
    [ "xmc_audio_source_port_t", "structxmc__audio__source__port__t.html", null ],
    [ "xmc_dma_config_t", "structxmc__dma__config__t.html", null ],
    [ "xmc_pwm_config_t", "structxmc__pwm__config__t.html", null ],
    [ "xmc_pwm_inst_t", "structxmc__pwm__inst__t.html", null ],
    [ "xmc_repeating_timer_t", "structxmc__repeating__timer__t.html", null ],
    [ "xmc_sdac_config_t", "structxmc__sdac__config__t.html", null ],
    [ "xmc_sdac_inst_t", "structxmc__sdac__inst__t.html", null ],
    [ "xmc_semaphore_t", "structxmc__semaphore__t.html", null ],
    [ "xmc_spinlock_t", "structxmc__spinlock__t.html", null ]
];