var hierarchy =
[
    [ "xmc::apFixed< TRaw, PREC >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::apFixed< int16_t, 12 >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::AppConfig", "structxmc_1_1AppConfig.html", null ],
    [ "xmc::AttributeBufferClass< T >", "classxmc_1_1AttributeBufferClass.html", null ],
    [ "xmc::BakedVertex", "structxmc_1_1BakedVertex.html", null ],
    [ "xmc::color4444", "unionxmc_1_1color4444.html", null ],
    [ "xmc::color4p12", "structxmc_1_1color4p12.html", null ],
    [ "xmc::colorf", "structxmc_1_1colorf.html", null ],
    [ "xmc::dma::Config", "structxmc_1_1dma_1_1Config.html", null ],
    [ "xmc::pwm::Config", "structxmc_1_1pwm_1_1Config.html", null ],
    [ "xmc::pwm::Driver", "classxmc_1_1pwm_1_1Driver.html", null ],
    [ "GFXfont", "structGFXfont.html", null ],
    [ "GFXglyph", "structGFXglyph.html", null ],
    [ "xmc::mat4", "structxmc_1_1mat4.html", null ],
    [ "xmc::Material3DClass", "classxmc_1_1Material3DClass.html", null ],
    [ "xmc::MatrixStackEntry", "structxmc_1_1MatrixStackEntry.html", null ],
    [ "xmc::Mesh3DClass", "classxmc_1_1Mesh3DClass.html", null ],
    [ "xmc::audio::Mixer", "classxmc_1_1audio_1_1Mixer.html", null ],
    [ "xmc::Node3DClass", "classxmc_1_1Node3DClass.html", null ],
    [ "xmc::Primitive3DClass", "classxmc_1_1Primitive3DClass.html", null ],
    [ "xmc::quat", "structxmc_1_1quat.html", null ],
    [ "xmc::RasterizerClass", "classxmc_1_1RasterizerClass.html", null ],
    [ "xmc::rect_t", "structxmc_1_1rect__t.html", null ],
    [ "xmc::RepeatingTimer", "classxmc_1_1RepeatingTimer.html", null ],
    [ "xmc::Scanner444", "structxmc_1_1Scanner444.html", null ],
    [ "xmc::Scene3DClass", "classxmc_1_1Scene3DClass.html", null ],
    [ "xmc::audio::SdacConfig", "structxmc_1_1audio_1_1SdacConfig.html", null ],
    [ "xmc::Semaphore", "classxmc_1_1Semaphore.html", null ],
    [ "xmc::audio::SourcePort", "structxmc_1_1audio_1_1SourcePort.html", null ],
    [ "xmc::SpinLock", "classxmc_1_1SpinLock.html", null ],
    [ "xmc::SpriteClass", "classxmc_1_1SpriteClass.html", [
      [ "xmc::Sprite4444Class", "classxmc_1_1Sprite4444Class.html", null ],
      [ "xmc::Sprite444Class", "classxmc_1_1Sprite444Class.html", null ],
      [ "xmc::Sprite565Class", "classxmc_1_1Sprite565Class.html", null ]
    ] ],
    [ "xmc::audio::StreamFormat", "structxmc_1_1audio_1_1StreamFormat.html", null ],
    [ "xmc::audio::StreamingDac", "classxmc_1_1audio_1_1StreamingDac.html", null ],
    [ "xmc::TextState", "structxmc_1_1TextState.html", null ],
    [ "xmc::audio::Tone", "classxmc_1_1audio_1_1Tone.html", null ],
    [ "xmc::TriangleInterp< PREC >", "structxmc_1_1TriangleInterp.html", null ],
    [ "xmc::vec2", "structxmc_1_1vec2.html", null ],
    [ "xmc::vec3", "structxmc_1_1vec3.html", null ]
];