var hierarchy =
[
    [ "xmc::apFixed< TRaw, PREC >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::apFixed< int32_t, 12 >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::apFixed< int32_t, 16 >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::apFixed< int32_t, 20 >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::apFixed< int32_t, 24 >", "structxmc_1_1apFixed.html", null ],
    [ "xmc::diagnostic::App", "classxmc_1_1diagnostic_1_1App.html", null ],
    [ "xmc::AppConfig", "structxmc_1_1AppConfig.html", null ],
    [ "xmc::AttributeBufferClass< T >", "classxmc_1_1AttributeBufferClass.html", null ],
    [ "xmc::BakedVertex", "structxmc_1_1BakedVertex.html", null ],
    [ "xmc::color4444", "unionxmc_1_1color4444.html", null ],
    [ "xmc::color8p24", "structxmc_1_1color8p24.html", null ],
    [ "xmc::colorf", "structxmc_1_1colorf.html", null ],
    [ "xmc::dma::Config", "structxmc_1_1dma_1_1Config.html", null ],
    [ "xmc::pwm::Config", "structxmc_1_1pwm_1_1Config.html", null ],
    [ "xmc::pwm::Driver", "classxmc_1_1pwm_1_1Driver.html", null ],
    [ "xmc::fs::File", "classxmc_1_1fs_1_1File.html", null ],
    [ "xmc::fs::FileInfo", "structxmc_1_1fs_1_1FileInfo.html", null ],
    [ "xmc::FpsKeeper", "classxmc_1_1FpsKeeper.html", null ],
    [ "xmc::FrameBuffer", "classxmc_1_1FrameBuffer.html", null ],
    [ "GFXfont", "structGFXfont.html", null ],
    [ "GFXglyph", "structGFXglyph.html", null ],
    [ "xmc::GlyphMetrics", "structxmc_1_1GlyphMetrics.html", null ],
    [ "xmc::GlyphRenderer", "classxmc_1_1GlyphRenderer.html", [
      [ "xmc::GlyphRendererAgfx", "classxmc_1_1GlyphRendererAgfx.html", null ]
    ] ],
    [ "xmc::Graphics2DClass", "classxmc_1_1Graphics2DClass.html", null ],
    [ "xmc::GraphicsState2D", "structxmc_1_1GraphicsState2D.html", null ],
    [ "xmc::mat4", "structxmc_1_1mat4.html", null ],
    [ "xmc::Material3DClass", "classxmc_1_1Material3DClass.html", null ],
    [ "xmc::MatrixStackEntry", "structxmc_1_1MatrixStackEntry.html", null ],
    [ "xmc::Mesh3DClass", "classxmc_1_1Mesh3DClass.html", null ],
    [ "xmc::audio::Mixer", "classxmc_1_1audio_1_1Mixer.html", null ],
    [ "xmc::Node3DClass", "classxmc_1_1Node3DClass.html", null ],
    [ "xmc::Primitive3DClass", "classxmc_1_1Primitive3DClass.html", null ],
    [ "xmc::quat", "structxmc_1_1quat.html", null ],
    [ "xmc::RasterizerClass", "classxmc_1_1RasterizerClass.html", null ],
    [ "xmc::RasterScan444", "classxmc_1_1RasterScan444.html", null ],
    [ "xmc::RasterScan4444", "classxmc_1_1RasterScan4444.html", null ],
    [ "xmc::RasterScan565", "classxmc_1_1RasterScan565.html", null ],
    [ "xmc::RasterScanGray1", "classxmc_1_1RasterScanGray1.html", null ],
    [ "xmc::Rect", "structxmc_1_1Rect.html", null ],
    [ "xmc::RepeatingTimer", "classxmc_1_1RepeatingTimer.html", null ],
    [ "xmc::ScanLineCounter", "structxmc_1_1ScanLineCounter.html", null ],
    [ "xmc::Scanner444", "structxmc_1_1Scanner444.html", null ],
    [ "xmc::Scene3DClass", "classxmc_1_1Scene3DClass.html", null ],
    [ "xmc::audio::SdacConfig", "structxmc_1_1audio_1_1SdacConfig.html", null ],
    [ "xmc::Semaphore", "classxmc_1_1Semaphore.html", null ],
    [ "xmc::audio::SourcePort", "structxmc_1_1audio_1_1SourcePort.html", null ],
    [ "xmc::SpinLock", "classxmc_1_1SpinLock.html", null ],
    [ "xmc::SpriteClass", "classxmc_1_1SpriteClass.html", [
      [ "xmc::Sprite4444Class", "classxmc_1_1Sprite4444Class.html", null ],
      [ "xmc::Sprite444Class", "classxmc_1_1Sprite444Class.html", null ],
      [ "xmc::Sprite565Class", "classxmc_1_1Sprite565Class.html", null ]
    ] ],
    [ "xmc::audio::StreamFormat", "structxmc_1_1audio_1_1StreamFormat.html", null ],
    [ "xmc::audio::StreamingDac", "classxmc_1_1audio_1_1StreamingDac.html", null ],
    [ "xmc::TextRenderArgs", "structxmc_1_1TextRenderArgs.html", null ],
    [ "xmc::TextureArgs", "structxmc_1_1TextureArgs.html", null ],
    [ "xmc::audio::Tone", "classxmc_1_1audio_1_1Tone.html", null ],
    [ "xmc::vec2", "structxmc_1_1vec2.html", null ],
    [ "xmc::vec3", "structxmc_1_1vec3.html", null ]
];